import { Inter } from 'next/font/google';
import './globals.css';
import ClientProvider from './store/ClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'My Next.js App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ClientProvider>
					{children}
				</ClientProvider>
			</body>
		</html>
	);
}
